import React from 'react'
import Head from 'next/head'

const faq = () => {
return (

<div>
  {/* ---------------------- Head ---------------------- */}

  <Head>
    <title>Bespoke Programming | FAQ</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/logo.svg" />
  </Head>

  <section id='faq'>

    <h3 className="heading">Frequently <br />Asked <br /><abbr className='purple'>Questions</abbr>.</h3>

    <div className="left">
      <h4>What do I need to run a website?</h4>
      <p>You will need a web hosting provider and a registered domain name. They are prerequisites to run a website and
        must be in place as soon as the project moves from the design phase into development. In essence, the web
        hosting
        provides you with an online space on the World Wide Web and the domain name (a.k.a. URL) is the path to that
        space. They can (and should) be bought from and registered with the same provider *.

        The hosting package is one of the main factors for website speed so it is very important to choose wisely - I
        would
        be happy to help with it and get everything registered and setup properly. There are quite a few options out
        there
        but after disappointing experiences with some of the most advertised providers, I came across IONOS (1AND1) many
        years ago and have been using them since for my personal projects and would strongly recommend them to you as
        well.

        * Web hosting and domain registration fees are paid directly to the chosen provider.</p>
    </div>

    <div className="right">
      <h4>How much does a new website cost?</h4>
      <p>The honest answer here is - it depends. It depends on the style of website you are looking for as they will
        require different types of functionality (informational, online shop, portfolio, etc), it depends on what you
        need
        me for in terms of services (web design or web development or both) and also, it depends on how much extra work
        will be required from me (photo editing, external plugins integration, etc).
        An ideal way to get a quote is by sending me an email or a message explaining what you have in mind and want to
        achieve with your project. In most cases I am able to provide a very close figure straight away.</p>
      <br /><br />

      <h4>How long does a new website take to be completed?</h4>
      <p>The answer is virtually the same as for the question above. To give you an idea, very basic websites can take
        between 4 to 6 weeks and more complex ones 8 to 12 weeks.</p>
      <br /><br />

      <h4>How about customisations and updates?</h4>
      <p>If you are only looking for customisations and updates on an existing website, the ideall way of geeting a
        quote
        and time frame is by sending me a list of changes you want to implement. In some cases I may need a bit more
        information but most of time I am able to provide you with a quote and time frame straight away.</p>
      <br /><br />

      <h4>How does support work after the website launch?</h4>
      <p>I am proud to say that I have kept long lasting relationships with my clients and I am always on hand to help
        them
        whenever needed with updates and further developments. Those are usually charged on an hourly bases.</p>
    </div>
  </section>
</div>
)
}

export default faq