import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bespoke Programming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <header>
        <Image
          src="/logo.svg"
          alt="logo"
          width={60}
          height={60}
        />
      </header>

      <main>
        <h1>Header number 1.</h1>
        <h2>Header number 2.</h2>
        <h3>Header number 3.</h3>
        <h4>Header number 4.</h4>
        <p>This is a paragraph.</p>
        <a href="#">Link</a>
      </main>
    </div>
  )
}
