import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bespoke Programming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <header>
        <nav>
          <Image
            src="/logo.svg"
            alt="logo"
            width={80}
            height={80}
          />
          <li>
            <a href="#">Home</a>
            <a href="#">Portfolio</a>
            <a href="#">Project</a>
            <a href="#">Services</a>
            <a href="#">Pricing</a>
            <a href="#">About</a>
            <a href="#">Contact</a>
            <a href="#">Policy</a>
          </li>
        </nav>
      </header>

      <main>
        <h1>Header number 1.</h1>
        <h2>Header number 2.</h2>
        <h3>Header number 3.</h3>
        <h4>Header number 4.</h4>
        <p>This is a paragraph.</p>
      </main>
    </div>
  )
}
